version: '3.8'

services:
  # React app service
  app:
    image: hemanth123456789/my-react-app:latest
    ports:
      - "3000:3000" 
    command: npm start # Map port 3000 of the container to port 3000 on the host
  # Mount the current directory to /app inside the container
  # Needed for file watching inside Docker (optional)

  # If you have a backend API, you could add a service for it as well:
  # api:
  #   image: your-backend-image
  #   ports:
  #     - "5000:5000"  # Example for a backend on port 5000
